services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: fairwave
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports: ["5432:5432"]
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d fairwave"]
      interval: 5s
      timeout: 3s
      retries: 30

  app:
    build: ./app
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    ports: ["8000:8000"]
    command: ["bash", "./start.sh"]
    volumes:
      - ./app:/srv/app    # dev hot-reload; remove for prod

volumes:
  dbdata:
